### ISSUE TITLE
Different wording needed 

### ISSUE THREAD

**Issue by Synchronicity89** [radian628/js-tutorial#1]
https://github.com/radian628/js-tutorial/blob/0e084e290a20cd799d8c164fd86119cd8c87c50d/days/day2.html#L214

The semantics of
if-statement(s) running

might confuse the student.  

The if statement **_is_** run to perform an evaluation.  It branches depending on the result.

**Comment by radian628** [comment]
Just fixed it- it now says
```html
                <p>Once. Only the first if-statement will execute the code between its curly braces.
```
